apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  containers:
  - image: mongo:4.4.19-rc0-focal
    volumeMounts:
      - mountPath: /data
        name: cephfs-shared-team-name
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        valueFrom:
          secretKeyRef:
            name: mongo-creds
            key: username
      - name: MONGO_INITDB_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mongo-creds
            key: password
    resources:
      requests:
        memory: "500M"
        cpu: "1"
      limits:
        memory: "500M"
        cpu: "1"
    command:
      - "sleep"
      - "7200"
    imagePullPolicy: IfNotPresent
    name: mongodb
  volumes:
    - name: cephfs-shared-team-name
      persistentVolumeClaim:
        claimName: cephfs-shared-team
  restartPolicy: Always
